### ISSUE TITLE
support: light.realraum.at

### ISSUE THREAD

**Issue by PeterTheOne** [realraum/deckenlichtschalter#7]
I get an error on load: `Error during WebSocket handshake: Unexpected response code: 403`.

May be because the websocket cross (sub)domain connects to `licht.realraum.at`.

**Comment by btittelbach** [comment]
should be fixed with commit 7d72139b6f27e810d15b8a6b028b97250948f348 (yeah: 100th commit)

**Comment by PeterTheOne** [comment]
Thanks!
